# Generated by Django 5.1.2 on 2024-10-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_sensordata_last_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='relay1_off_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='relay1_on_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='relay2_off_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='relay2_on_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='relay3_off_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='relay3_on_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='relay4_off_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='relay4_on_time',
            field=models.IntegerField(default=0),
        ),
    ]
