# Generated by Django 5.1.2 on 2024-10-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_sensordata_relay1_off_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='relay1_off_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='relay1_on_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='relay2_off_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='relay2_on_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='relay3_off_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='relay3_on_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='relay4_off_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='relay4_on_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
