# Generated by Django 5.1.2 on 2024-10-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_sensordata_relay1_off_time_sensordata_relay1_on_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay_id', models.IntegerField()),
                ('on_time', models.IntegerField()),
                ('off_time', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
